Repository parti-renaissance/espace-cadre, pull requests merged in 2021-05, with the labels that each got.

#94 Rearrange Style files
  package.json
  src/App.jsx
  src/components/ContactsPage/ColumnsContentRendering/BooleanRendering.scss/BooleanRendering.jsx
  src/components/ContactsPage/ColumnsContentRendering/BooleanRendering/BooleanRendering.jsx
  src/components/ContactsPage/ColumnsContentRendering/BooleanRendering/BooleanRendering.scss
  src/components/ContactsPage/ColumnsContentRendering/InterestRendering/InterestRendering.jsx
  src/components/ContactsPage/ContactsComponent/Contacts.jsx
  src/components/ContactsPage/ContactsComponent/Contacts.scss
  src/components/ContactsPage/Filters/BooleanSelectFilter/BooleanSelectFilter.jsx
  src/components/ContactsPage/Filters/BooleanSelectFilter/BooleanSelectFilter.scss
  src/components/ContactsPage/Filters/ColumnFilter/ColumnFilter.scss
  src/components/ContactsPage/Filters/GlobalFilter/GlobalFilter.jsx
  src/components/ContactsPage/Filters/MultiSelectFilter/MultiSelectFilter.jsx
  src/components/ContactsPage/Filters/SelectFilter/SelectFilter.jsx
  src/components/ContactsPage/Filters/SelectFilter/SelectFilter.scss
  src/components/ContactsPage/Table/Table.jsx
  src/components/DashboardComponent/Dashboard.scss
  src/components/Mail/Audience/Audience.jsx
  src/components/Mail/Mail.jsx
  src/components/Mail/Template/Template.jsx
  src/components/Mail/Template/grapesjs/Editor.jsx
  src/components/Root/Root.jsx
  src/components/Sidebar/Sidebar.jsx
  src/style/DOMElements/_global_style.scss
  src/style/DOMElements/index.scss
  src/style/_main.scss
  src/style/components/_App.scss
  src/style/components/_Audience.scss
  src/style/components/_BooleanRendering.scss
  src/style/components/_Editor.scss
  src/style/components/_GlobalFilter.scss
  src/style/components/_InterestRendering.scss
  src/style/components/_Mail.scss
  src/style/components/_MultiSelectFilter.scss
  src/style/components/_Root.scss
  src/style/components/_Sidebar.scss
  src/style/components/_Table.scss
  src/style/components/_Template.scss
  src/style/components/index.scss
  src/style/helpers/_mixins.scss
  src/style/helpers/_variables.scss
  src/style/helpers/index.scss
  src/style/index.scss
  yarn.lock
Labels: RFR

#92 Dashboard page with charts
  package.json
  src/components/ContactsPage/Filters/MultiSelectFilter/MultiSelectFilter.jsx
  src/components/DashboardComponent/Charts/ActiveUsersComponent/ActiveUsersComponent.jsx
  src/components/DashboardComponent/Charts/DownloadsCountComponent/DownloadsCountComponent.jsx
  src/components/DashboardComponent/Dashboard.jsx
  src/components/Root/Switch.jsx
  src/style/components/_ActiveUsersComponent.scss
  src/style/components/_Dashboard.scss
  src/style/components/_DownloadsCountComponent.scss
  src/style/components/index.scss
  yarn.lock
Labels: RFR

#100 Keep only send button
  .eslintrc.json
  public/favicon.png
  public/index.html
  src/components/Loader/Loader.jsx
  src/components/Loader/index.js
  src/components/Mail/Mail.jsx
  src/components/Mail/Template/Editor.jsx
  src/components/Mail/Template/Template.jsx
  src/components/Mail/Template/index.js
  src/components/Mail/index.js
  src/components/Root/Root.jsx
  src/components/Root/Switch.jsx
  src/redux/template/hooks.js
  src/services/networking/client.js
  src/style/components/_App.scss
  src/style/components/_Loader.scss
  src/style/components/_Mail.scss
  src/style/components/_Root.scss
  src/style/components/index.scss
Labels: WIP

#106 A bit of style everywhere
  src/components/Sidebar/Sidebar.jsx
  src/style/components/_Root.scss
  src/style/components/_Sidebar.scss
Labels: WIP

#112 Staging + Prod
  .github/workflows/Build_Docker.yml
  .github/workflows/Publish_Cloud_Run - Staging.yml
  .github/workflows/Publish_Cloud_Run -Release.yml
Labels: enhancement

#116 Apply fixes from CodeFactor
  src/style/components/_Sidebar.scss
Labels: enhancement

#120 Improve GitHub CI & CD workflow
  .github/workflows/Build_Docker.yml
  .github/workflows/Publish_Cloud_Run - Staging.yml
  .github/workflows/Publish_Cloud_Run -Release.yml
  .github/workflows/ci-cd.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/test.yml
Labels: WIP

#124 Style for messagerie page
  src/components/Mail/Template/Editor.jsx
  src/components/Mail/Template/Template.jsx
  src/style/components/_Editor.scss
  src/style/components/_Template.scss
Labels: RFR

#119 Init geo data
  package.json
  public/index.html
  src/components/DashboardComponent/Dashboard.jsx
  src/components/DashboardComponent/Map/MapComponent.jsx
  src/style/components/MapComponent.scss
  src/style/components/_Dashboard.scss
  src/style/components/index.scss
  src/style/index.scss
  yarn.lock
Labels: RFR

#125 Update zoom map
  public/images/layers-2x.png
  public/images/layers.png
  public/images/marker-icon-2x.png
  public/images/marker-icon.png
  public/images/marker-shadow.png
  src/components/DashboardComponent/Charts/ActiveUsersComponent/ActiveUsersComponent.jsx
  src/components/DashboardComponent/Charts/DownloadsCountComponent/DownloadsCountComponent.jsx
  src/components/DashboardComponent/Map/MapComponent.jsx
  src/components/Sidebar/Sidebar.jsx
  src/style/components/_ActiveUsersComponent.scss
  src/style/components/_DownloadsCountComponent.scss
  src/style/components/_Sidebar.scss
Labels: WIP

#135 New button hover
  src/components/Mail/Template/Template.jsx
  src/style/components/_App.scss
  src/style/components/_Template.scss
  src/style/helpers/_mixins.scss
  src/style/helpers/_variables.scss
Labels: RFR

#133 Add popup with info
  src/components/Dashboard/Map/MapComponent.jsx
  src/style/DOMElements/_global_style.scss
  src/style/components/_ActiveUsersComponent.scss
  src/style/components/_DownloadsCountComponent.scss
  src/style/components/_GlobalFilter.scss
  src/style/components/_Root.scss
  src/style/components/_Sidebar.scss
  src/style/components/_Table.scss
  src/style/components/_Template.scss
Labels: RFR

#138 EM-875 Introduce tests
  .eslintrc.json
  package.json
  src/components/Dashboard/Charts/ActiveUsers.test.jsx
  src/components/Dashboard/Charts/TextChart.jsx
  src/components/Dashboard/Charts/TextChart.test.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/Mail/Template/Template.test.jsx
  src/redux/configureStore.js
  src/setupTests.js
  yarn.lock
Labels: RFR

#147 Enable tests on CI
  .github/workflows/ci-cd.yaml
  src/components/Dashboard/Charts/TextChart.test.jsx
  src/components/Mail/Template/TemplateSelect.jsx
Labels: RFR

#149 Fix button test error
  src/components/Mail/Template/Template.test.jsx
Labels: RFR

#145 Redesign dashboard page
  src/Routes.jsx
  src/components/Dashboard/Charts/ActiveUsers/ActiveUsers.jsx
  src/components/Dashboard/Charts/ActiveUsers/ActiveUsers.test.jsx
  src/components/Dashboard/Charts/DownloadsCount/DownloadsCount.jsx
  src/components/Dashboard/Charts/DownloadsRatios/DownloadsRatios.jsx
  src/components/Dashboard/Charts/TextChart/TextChart.jsx
  src/components/Dashboard/Charts/TextChart/TextChart.test.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/Map/MapComponent.jsx
  src/style/components/_Dashboard.scss
Labels: WIP

#162 Dashboard redux
  src/components/Dashboard/Charts/ActiveUsers/ActiveUsers.jsx
  src/components/Dashboard/Charts/ActiveUsers/ActiveUsers.test.jsx
  src/components/Dashboard/Charts/DownloadsCount/DownloadsCount.jsx
  src/components/Dashboard/Charts/DownloadsRatios/DownloadsRatios.jsx
  src/components/Dashboard/Charts/TextChart/TextChart.jsx
  src/components/Dashboard/Charts/TextChart/TextChart.test.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/Map/MapComponent.jsx
  src/redux/dashboard/hooks.js
  src/redux/dashboard/index.js
  src/redux/dashboard/selectors.js
  src/redux/dashboard/slice.js
  src/redux/reducers/index.js
Labels: RFR

#166 Redux for contacts page
  src/components/ContactsPage/Contacts.jsx
  src/components/ContactsPage/Table/Table.jsx
  src/redux/contacts/hooks.js
  src/redux/contacts/index.js
  src/redux/contacts/selectors.js
  src/redux/contacts/slice.js
  src/redux/reducers/index.js
Labels: RFR

#167 Remove useless scrollbar + css
  src/style/components/_Editor.scss
  src/style/components/_Table.scss
  src/style/components/index.scss
Labels: WIP

#169 EM-926 email campaigns
  src/components/Dashboard/Charts/EmailCampaign/EmailCampaign.jsx
  src/components/Dashboard/Dashboard.jsx
  src/redux/dashboard/hooks.js
  src/redux/dashboard/selectors.js
  src/redux/dashboard/slice.js
  src/style/components/EmailCampaign.scss
  src/style/components/_Dashboard.scss
  src/style/components/index.scss
Labels: WIP

#179 Improvements mail campaigns
  public/images/mail.svg
  public/images/smartphone.svg
  src/Routes.jsx
  src/components/Dashboard/Charts/EmailCampaign/EmailCampaign.jsx
  src/components/Dashboard/Charts/TextChart/TextChart.jsx
  src/components/Dashboard/Dashboard.jsx
  src/style/components/EmailCampaign.scss
  src/style/components/_EmailCampaign.scss
  src/style/components/_TextChart.scss
  src/style/components/index.scss
Labels: RFR

#181 Function to convert to % + handle plural/singular
  src/components/ContactsPage/Table/Table.jsx
  src/components/Dashboard/Charts/ActiveUsers/ActiveUsers.jsx
  src/components/Dashboard/Charts/DownloadsCount/DownloadsCount.jsx
  src/components/Dashboard/Charts/EmailCampaign/EmailCampaign.jsx
  src/components/Dashboard/Charts/TextChart/TextChart.jsx
  src/components/Dashboard/Map/MapComponent.jsx
Labels: RFR

#184 Improvements for contacts page
  public/favicon_dc.png
  public/index.html
  src/components/ContactsPage/Table/Table.jsx
  src/style/components/_Table.scss
Labels: RFR

#186 Convert to percent component
  src/components/ConvertToPercent/ConvertToPercent.jsx
  src/components/Dashboard/Charts/EmailCampaign/EmailCampaign.jsx
Labels: RFR
