Repository parti-renaissance/espace-cadre, pull requests merged in 2021-06, with the labels that each got.

#190 EM-964 Mentions légales
  src/components/MentionsLegales/MentionsLegales.jsx
  src/components/Sidebar/Sidebar.jsx
  src/style/components/_MentionsLegales.scss
  src/style/components/_Sidebar.scss
  src/style/components/index.scss
  src/style/helpers/_variables.scss
Labels: RFR

#193 Add app version var env
  .env
  .github/workflows/ci-cd.yaml
  src/components/MentionsLegales/MentionsLegales.jsx
  src/style/components/_MentionsLegales.scss
Labels: RFR

#197 Rebrand logo
  public/images/bar-chart.svg
  src/components/Sidebar/Sidebar.jsx
  src/style/components/_Sidebar.scss
Labels: RFR

#203 EM-992 Update wording
  src/components/Dashboard/Charts/ActiveUsers/ActiveUsers.jsx
  src/components/Dashboard/Charts/DownloadsCount/DownloadsCount.jsx
Labels: RFR

#204 Update message page style
  src/components/Dashboard/Charts/SentEmailCampaignList/SentEmailCampaignList.jsx
  src/style/components/_Messagerie.scss
  src/style/components/_SentEmailCampaign.scss
Labels: WIP

#205 Hover modifications for email editor
  src/components/Mail/Template/TemplateSelect.jsx
  src/style/helpers/_buttons.scss
Labels: RFR

#225 Filters by election and by tour
  src/components/ContactsPage/Table/Table.jsx
  src/components/Elections/ElectionTable.jsx
  src/components/Elections/Elections.jsx
  src/style/components/_Elections.scss
  src/style/components/_Table.scss
Labels: RFR

#229 Add nuance in popup
  src/components/Elections/ElectionTable.jsx
  src/style/components/_Elections.scss
Labels: RFR

#230 Display title line once
  src/components/Elections/ElectionTable.jsx
  src/components/Elections/Elections.jsx
  src/style/components/_Elections.scss
Labels: WIP

#231 Update nginx 1.20
  Dockerfile
Labels: dependencies, security

#232 Improve popup content
  src/components/Elections/Elections.jsx
  src/style/components/_Elections.scss
Labels: WIP

#240 Add all candidates results in popup
  src/components/Elections/Elections.jsx
  src/style/components/_Elections.scss
Labels: WIP

#246 Update map size and overlay
  src/style/components/_Elections.scss
Labels: WIP

#247 Add name of the clicked area in popup
  src/components/Elections/Elections.jsx
  src/style/components/_Elections.scss
Labels: WIP

#257 Init dropdown
  public/images/list.svg
  public/images/vector.svg
  src/components/PageContent/PageContent.jsx
  src/components/Root/Root.jsx
  src/components/Scopes/Scopes.jsx
  src/components/Scopes/index.js
  src/redux/auth/hooks.js
  src/redux/auth/slice.js
  src/redux/user/selectors.js
  src/style/components/_Root.scss
  src/style/helpers/_variables.scss
Labels: RFR
