Repository parti-renaissance/espace-cadre, pull requests merged in 2021-04, with the labels that each got.

#2 Mail page
  package.json
  src/App.jsx
  src/components/Mail/Audience/Audience.jsx
  src/components/Mail/Audience/Audience.scss
  src/components/Mail/Mail.jsx
  src/components/Mail/Mail.scss
  src/components/Mail/Template/Template.jsx
  src/components/Mail/Template/Template.scss
  src/components/Mail/Template/grapesjs/Editor.jsx
  src/components/Mail/Template/grapesjs/Editor.scss
  src/components/Sidebar/Sidebar.jsx
  yarn.lock
Labels: WIP

#3 Display dynamically columns titles
  src/components/Contacts/Contacts.jsx
  src/components/Sidebar/Sidebar.jsx
Labels: enhancement

#32 Contacts page improvements
  src/components/Contacts/Contacts.jsx
  src/components/Root/Root.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Spinner/Spinner.jsx
Labels: WIP

#34 Contact page improvements
  package.json
  src/components/Contacts/ColumnsRendering/InterestCenter.jsx
  src/components/Contacts/Contacts.jsx
  src/components/Contacts/Filters/ColumnFilter.jsx
  src/components/Contacts/Filters/GlobalFilter.jsx
  src/components/Contacts/Filters/MultiSelectFilter.jsx
  src/components/Contacts/Filters/SelectFilter.jsx
  src/components/Contacts/TableContainer/TableContainer.jsx
  src/components/Contacts/TableContainer/TableContainer.scss
  src/components/Sidebar/Sidebar.jsx
  yarn.lock
Labels: WIP

#45 Wip contacts page + fix new table structure
  package.json
  src/components/ContactsPage/ColumnsContentRendering/BooleanRendering.jsx
  src/components/ContactsPage/ColumnsContentRendering/InterestRendering.jsx
  src/components/ContactsPage/ContactsComponent/Contacts.jsx
  src/components/ContactsPage/Filters/BooleanSelectFilter.jsx
  src/components/ContactsPage/Filters/MultiSelectFilter.jsx
  src/components/ContactsPage/Table/Table.jsx
  src/components/ContactsPage/Table/Table.scss
  yarn.lock
Labels: WIP

#48 Logout user
  .env
  .eslintrc.json
  package.json
  src/components/Root/Root.jsx
  src/redux/auth/hooks.js
  src/redux/auth/slice.js
  src/services/networking/client.js
Labels: RFR

#54 [CodeQuality] Enable Airbnb eslint plugin
  .eslintrc.json
  src/components/ContactsPage/ColumnsContentRendering/BooleanRendering.jsx
  src/components/ContactsPage/ColumnsContentRendering/InterestRendering.jsx
  src/components/ContactsPage/ContactsComponent/Contacts.jsx
  src/components/ContactsPage/Filters/BooleanSelectFilter.jsx
  src/components/ContactsPage/Filters/ColumnFilter.jsx
  src/components/ContactsPage/Filters/GlobalFilter.jsx
  src/components/ContactsPage/Filters/MultiSelectFilter.jsx
  src/components/ContactsPage/Filters/SelectFilter.jsx
  src/components/ContactsPage/Table/Table.jsx
  src/components/ContactsPage/Table/Table.scss
  src/components/Mail/Audience/Audience.jsx
  src/components/Mail/Mail.jsx
  src/components/Mail/Template/Template.jsx
  src/components/Mail/Template/grapesjs/Config.jsx
  src/components/Mail/Template/grapesjs/Editor.jsx
  src/components/Root/Root.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Spinner/Spinner.jsx
  src/redux/auth/hooks.js
  src/services/networking/client.js
Labels: RFR

#52 Use internal api client for contacts page
  .env
  .github/workflows/google.yml
  Dockerfile
  src/components/ContactsPage/ContactsComponent/Contacts.jsx
  src/components/ContactsPage/Filters/MultiSelectFilter.jsx
  src/redux/auth/hooks.js
  src/services/networking/client.js
Labels: RFR, security

#51 [EM-643][Email] Move openblock trigger to onload listener
  src/components/Mail/Audience/Audience.scss
  src/components/Mail/Template/Template.scss
  src/components/Mail/Template/grapesjs/Config.js
  src/components/Mail/Template/grapesjs/Editor.jsx
  src/components/Mail/Template/grapesjs/editor-content.html
Labels: Email Editor, RFR, bug

#56 Fix getAccessToken static call
  Dockerfile
  src/services/networking/client.js
Labels: bug

#41 Editors Changes / Template empty and Blocks
  src/components/Mail/Audience/Audience.jsx
  src/components/Mail/Mail.scss
  src/components/Mail/Template/Template.jsx
  src/components/Mail/Template/Template.scss
  src/components/Mail/Template/grapesjs/Config.js
  src/components/Mail/Template/grapesjs/Editor.jsx
  src/components/Mail/Template/grapesjs/Editor.scss
  src/services/networking/client.js
Labels: Email Editor

#59 WIP interests filter
  src/components/ContactsPage/Filters/MultiSelectFilter.jsx
  src/components/ContactsPage/Filters/MultiSelectFilter2.jsx
  src/components/ContactsPage/Table/Table.jsx
Labels: WIP

#61 Filter for interests
  src/components/ContactsPage/ContactsComponent/Contacts.jsx
  src/components/ContactsPage/Filters/MultiSelectFilter.jsx
  src/components/ContactsPage/Filters/MultiSelectFilter2.jsx
Labels: WIP

#64 Load Bootstrap package in JS
  .eslintrc.json
  public/index.html
  src/App.jsx
Labels: RFR

#67 WIP style
  src/App.scss
  src/components/ContactsPage/ContactsComponent/Contacts.jsx
  src/components/ContactsPage/Filters/GlobalFilter/GlobalFilter.jsx
  src/components/ContactsPage/Filters/GlobalFilter/GlobalFilter.scss
  src/components/ContactsPage/Table/Table.jsx
  src/components/ContactsPage/Table/Table.scss
  src/components/Root/Root.jsx
  src/components/Root/Root.scss
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.scss
  src/style/basics/_buttons.scss
  src/style/helpers/_fonts.scss
  src/style/helpers/_variables.scss
  src/style/main.scss
Labels: WIP

#68 WIP Contacts page style
  src/components/ContactsPage/ContactsComponent/Contacts.jsx
  src/components/ContactsPage/Filters/BooleanSelectFilter/BooleanSelectFilter.jsx
  src/components/ContactsPage/Filters/BooleanSelectFilter/BooleanSelectFilter.scss
  src/components/ContactsPage/Filters/ColumnFilter/ColumnFilter.jsx
  src/components/ContactsPage/Filters/ColumnFilter/ColumnFilter.scss
  src/components/ContactsPage/Filters/GlobalFilter/GlobalFilter.scss
  src/components/ContactsPage/Filters/MultiSelectFilter/MultiSelectFilter.jsx
  src/components/ContactsPage/Filters/MultiSelectFilter/MultiSelectFilter.scss
  src/components/ContactsPage/Filters/SelectFilter/SelectFilter.jsx
  src/components/ContactsPage/Filters/SelectFilter/SelectFilter.scss
  src/components/ContactsPage/Table/Table.jsx
  src/components/ContactsPage/Table/Table.scss
  src/components/Mail/Template/Template.scss
  src/components/Root/Root.scss
  src/style/DOMElements/_basics.scss
  src/style/basics/_buttons.scss
  src/style/main.scss
Labels: WIP

#69 Improve Interests filter
  src/components/ContactsPage/ContactsComponent/Contacts.jsx
  src/components/ContactsPage/Filters/MultiSelectFilter/MultiSelectFilter.jsx
Labels: RFR

#71 WIP Style
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.scss
Labels: WIP

#72 WIP Style for page Contacts
  src/components/ContactsPage/ColumnsContentRendering/InterestRendering/InterestRendering.jsx
  src/components/ContactsPage/ColumnsContentRendering/InterestRendering/InterestRendering.scss
  src/components/ContactsPage/ContactsComponent/Contacts.jsx
  src/components/ContactsPage/Table/Table.jsx
  src/components/ContactsPage/Table/Table.scss
  src/style/DOMElements/_globalStyle.scss
  src/style/main.scss
Labels: WIP

#74 Style for page Contacts
  src/components/ContactsPage/ColumnsContentRendering/InterestRendering/InterestRendering.jsx
  src/components/ContactsPage/ColumnsContentRendering/InterestRendering/InterestRendering.scss
  src/components/ContactsPage/Table/Table.jsx
  src/components/ContactsPage/Table/Table.scss
Labels: WIP

#76 Style for contacts page
  src/App.scss
  src/components/ContactsPage/Table/Table.jsx
  src/components/ContactsPage/Table/Table.scss
Labels: WIP

#77 WIP - Contacts page improvements
  src/components/ContactsPage/ColumnsContentRendering/InterestRendering/InterestRendering.jsx
  src/components/ContactsPage/ColumnsContentRendering/InterestRendering/InterestRendering.scss
  src/components/ContactsPage/Filters/GlobalFilter/GlobalFilter.scss
  src/components/ContactsPage/Table/Table.jsx
  src/components/ContactsPage/Table/Table.scss
  src/components/Mail/Template/Template.scss
  src/components/Root/Root.jsx
  src/components/Root/Root.scss
  src/components/Root/Switch.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.scss
  src/style/DOMElements/_basics.scss
Labels: WIP

#81 WIP Contacts page
  src/components/ContactsPage/Filters/GlobalFilter/GlobalFilter.jsx
  src/components/ContactsPage/Table/Table.jsx
  src/components/Root/Root.scss
  src/components/Root/Switch.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.scss
  src/style/DOMElements/_basics.scss
Labels: WIP

#82 Contacts page
  src/components/Auth/Auth.jsx
  src/components/ContactsPage/ContactsComponent/Contacts.jsx
  src/components/ContactsPage/Table/Table.jsx
  src/components/ContactsPage/Table/Table.scss
Labels: RFR

#86 [EM-714][Mail] Enable AssetManager and upload images to backend
  src/components/Mail/Template/grapesjs/Editor.jsx
  src/services/networking/client.js
Labels: RFR

#88 Add Dashboard link in sidebar
  src/components/DashboardComponent/Dashboard.jsx
  src/components/DashboardComponent/Dashboard.scss
  src/components/Root/Switch.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.scss
Labels: WIP

#89 Introduce mixins
  src/components/ContactsPage/ColumnsContentRendering/BooleanRendering.scss/BooleanRendering.jsx
  src/components/ContactsPage/ColumnsContentRendering/BooleanRendering.scss/BooleanRendering.scss
  src/components/ContactsPage/ColumnsContentRendering/InterestRendering/InterestRendering.scss
  src/components/ContactsPage/ContactsComponent/Contacts.jsx
  src/components/ContactsPage/ContactsComponent/Contacts.scss
  src/components/ContactsPage/Filters/GlobalFilter/GlobalFilter.scss
  src/components/ContactsPage/Table/Table.scss
  src/components/Mail/Template/Template.scss
  src/components/Root/Root.scss
  src/style/DOMElements/_basics.scss
  src/style/DOMElements/_globalStyle.scss
  src/style/DOMElements/_mixins.scss
  src/style/_main.scss
  src/style/helpers/_variables.scss
Labels: WIP
