Repository parti-renaissance/espace-cadre, pull requests merged in 2022-05, with the labels that each got.

#1469 [LPN-768] Events: Fix datetime on event card
  src/components/Events/card/Header.js
  src/components/News/ReadModal.js
  src/ui/Card/Title/Title.js
Labels: RFR

#1463 [LPN-753] Add presidentials 2nd round
  src/components/Elections/ElectionFilters.js
  src/components/Elections/shared/constants.js
Labels: RFR

#1471 make cleanRetry first action
  src/components/useRetry.js
Labels: RFR

#1479 Update pap legislatives mapbox
  src/components/Map/Layers.js
Labels: RFR

#1470 [CHORE] Improve cypress perfs
  cypress/fixtures/scopes.json
  cypress/integration/DTD.spec.js
  cypress/integration/activists.spec.js
  cypress/integration/dashboard.spec.js
  cypress/integration/events.spec.js
  cypress/integration/groups.spec.js
  cypress/integration/main.spec.js
  cypress/integration/messagerie.spec.js
  cypress/integration/my-team-create-edit.spec.js
  cypress/integration/my-team.spec.js
  cypress/integration/news.spec.js
  cypress/integration/phoning-campaign.spec.js
  cypress/integration/phoning.spec.js
  cypress/integration/ripostes.spec.js
  cypress/integration/surveys-create-edit.spec.js
  cypress/integration/surveys.spec.js
Labels: RFR

#1484 Upgrade mui material & system
  package.json
  yarn.lock
Labels: RFR

#1486 [LPN-778] Refetch auto for surveys
  src/components/Surveys/Surveys.js
Labels: RFR

#1488 Add cypress tests for news
  cypress/fixtures/news/news.json
  cypress/integration/news.spec.js
  src/components/News/Card/Header.js
Labels: RFR

#1491 [CHORE] Remove DTD local map
  src/components/DTDLegislatives/DTDLegislatives.js
Labels: RFR

#1526 [DTD] remove additional map layer
  src/components/DTDLegislatives/Map.js
Labels: RFR

#1466 [LPN-762] New legislatives candidate template
  src/components/Messagerie/Component/Editor.js
Labels: RFR

#1530 Add logout action for switched user
  src/components/Auth/Auth.js
  src/components/Logout/Logout.js
  src/components/Scopes/Scopes.js
  src/redux/auth/hooks.js
  src/redux/auth/slice.js
  src/redux/user/selectors.js
Labels: RFR

#1541 [LPN-470] Display error for groups
  src/components/Groups/GroupModal.js
  src/components/Groups/Groups.js
Labels: RFR

#1543 [DTDMap] allow manual zoom and move
  src/components/DTDLegislatives/Map.js
Labels: RFR

#1550 [LPN-839] Height for DTD local map
  src/components/DTDLegislatives/CreateEditModal.js
  src/components/DTDLegislatives/DTDLegislatives.js
  src/components/DTDLegislatives/Map.js
  src/components/DTDLegislatives/styles.css
Labels: RFR

#1564 [LPN-850] Cypress tests for groups feature
  cypress/integration/groups.spec.js
  src/components/Groups/GroupModal.js
Labels: RFR

#1573 Cypress - Add tests for action numérique
  cypress/fixtures/ripostes/ripostes.json
  cypress/integration/groups.spec.js
  cypress/integration/ripostes.spec.js
  src/components/Ripostes/Card/Content.js
  src/components/Ripostes/CreateEditModal.js
Labels: RFR

#1583 [LPN-861] Events: display backend errors + fix update
  src/components/Events/CreateEditEvent.js
  src/ui/Stepper/Stepper.js
Labels: RFR

#1588 [LPN-852] Delete PAP campaign
  src/api/DTD.js
  src/components/DTDLegislatives/Campaign/CampaignItem.js
  src/components/DTDLegislatives/DTDLegislatives.js
Labels: WIP

#1589 [Phoning] return null as default value for boolean filters
  src/components/Phoning/CampaignDetail/shared/helpers.js
Labels: bug, RFR
