Repository parti-renaissance/espace-cadre, pull requests merged in 2023-02, with the labels that each got.

#1917 [LPN-1410] add new my team member role
  src/components/MyTeam/shared/constants.js
Labels: Ready for code review

#1918 Lpn 1361 - elected representatives lists
  src/api/elected-representative.js
  src/components/ElectedRepresentative/Dashboard.jsx
  src/components/ElectedRepresentative/index.jsx
  src/components/Messagerie/index.jsx
  src/providers/routes.jsx
  src/providers/styles.js
  src/shared/constants.js
  src/shared/features.js
  src/shared/paths.js
  src/style/_layout.scss
  src/style/base.scss
  src/style/index.scss
  src/style/pages/elected.scss
  src/style/partials/_utilities.scss
Labels: Ready for code review

#1919 [Adherents] display phone number
  src/api/activist.js
  src/components/Activists/TableBodyComponent.jsx
  src/domain/activist.js
Labels: RFR

#1920 enabled filters for elected representative
  src/api/elected-representative.js
  src/api/filters.js
  src/components/ElectedRepresentative/Dashboard.jsx
  src/components/Filters/DynamicFilters.jsx
  src/components/Filters/FiltersFactory/Factory/SelectFactory.jsx
  src/ui/EmptyContent/EmptyContent.jsx
Labels: Ready for code review

#1922 Create elected representative form
  src/api/elected-representative.js
  src/components/ElectedRepresentative/CreateEditModal.jsx
  src/components/ElectedRepresentative/Dashboard.jsx
  src/style/_variables.scss
  src/style/index.scss
  src/style/partials/_forms.scss
  src/ui/Button/Button.jsx
Labels: Ready for code review

#1923 [DynamicFilters] change filters endpoint
  cypress/e2e/activists.cy.js
  src/api/filters.js
  src/components/Activists/Activists.jsx
  src/components/ElectedRepresentative/Dashboard.jsx
  src/components/Events/CreateEditEvent.jsx
  src/components/Filters/DynamicFilters.jsx
  src/components/Messagerie/Filters.jsx
  src/services/networking/client.js
  src/shared/features.js
Labels: RFR

#1924 Lpn 1361 display elected
  src/components/ElectedRepresentative/CreateEditModal.jsx
  src/components/ElectedRepresentative/Dashboard.jsx
  src/components/ElectedRepresentative/ElectedDetail.jsx
  src/components/ElectedRepresentative/index.jsx
  src/style/partials/_utilities.scss
  src/style/utilities/_spacing.scss
  src/ui/PageHeader/PageHeader.jsx
  src/ui/PageTitle/PageTitle.jsx
Labels: Ready for code review

#1925 [DptSite] improve site editor
  .env
  .github/actions/deploy/action.yml
  .github/workflows/ci-cd.yaml
  src/api/departmental-site.js
  src/api/site.js
  src/components/Site/Component/Editor.jsx
  src/components/Site/DepartmentSite.jsx
  src/shared/environments.js
Labels: RFR

#1921 fix ui bug display
  cypress/e2e/phoning-campaign.cy.js
  src/components/Layout/NavMenu.jsx
  src/components/Layout/Navigation.jsx
  src/components/Layout/shared/icons.jsx
  src/shared/features.js
  src/style/_layout.scss
Labels: Ready for code review

#1928 Add Adherent autocomplete component
  src/api/activist.js
  src/components/DTD/CampaignDetail/CampaignDetail.jsx
  src/components/DTDLegislatives/CampaignDetail/CampaignDetail.jsx
  src/components/ElectedRepresentative/CreateEditModal.jsx
  src/components/Filters/Element/AdherentAutocomplete.jsx
  src/components/Filters/Element/Autocomplete.jsx
  src/components/Groups/GroupEdit.jsx
  src/components/Phoning/CampaignDetail/CampaignDetail.jsx
Labels: Ready for code review

#1926 Lpn 1361 create edit mandate
  src/api/elected-representative.js
  src/api/phoning.js
  src/components/ElectedRepresentative/CreateEditMandate.jsx
  src/components/ElectedRepresentative/CreateEditModal.jsx
  src/components/ElectedRepresentative/ElectedDetail.jsx
  src/components/Filters/Element/ZoneAutocomplete.jsx
  src/shared/constants.js
  src/ui/Button/Button.jsx
  src/ui/Button/ConfirmButton.jsx
  src/ui/Confirmation/ConfrmationModal.jsx
  src/ui/Confirmation/index.js
  src/ui/Title/Title.jsx
  src/ui/Title/index.js
Labels: Ready for code review

#1935 Lpn 1347 create | update formation
  package.json
  src/api/formations.js
  src/components/Formations/CreateEditModal.jsx
  src/components/Formations/Formations.jsx
  src/services/networking/client.js
  src/style/_buttons.scss
  yarn.lock
Labels: Ready for code review

#1939 [Elected] fix pagination
  src/components/ElectedRepresentative/Dashboard.jsx
Labels: bug, Ready for code review

#1940 Update react-query v4
  package.json
  src/api/useQueryWithScope.js
  src/components/DTDLegislatives/CreateEditModal.jsx
  src/components/DTDLegislatives/DTDLegislatives.jsx
  src/components/DTDLegislatives/Modal/step02/PollingStationSelect.jsx
  src/components/Dashboard/Charts/SentEmailCampaigns/SentEmailCampaigns.jsx
  src/components/ElectedRepresentative/CreateEditMandate.jsx
  src/components/ElectedRepresentative/CreateEditModal.jsx
  src/components/ElectedRepresentative/ElectedDetail.jsx
  src/components/Events/CreateEditEvent.jsx
  src/components/Events/EventList.jsx
  src/components/Events/Events.jsx
  src/components/Formations/CreateEditModal.jsx
  src/components/Formations/Formations.jsx
  src/components/GeneralReports/CreateEditModal.jsx
  src/components/Groups/GroupEdit.jsx
  src/components/Groups/GroupModal.jsx
  src/components/Groups/Groups.jsx
  src/components/Messagerie/Filters.jsx
  src/components/MyTeam/CreateEdit/CreateEdit.jsx
  src/components/MyTeam/MyTeam.jsx
  src/components/News/CreateEditModal.jsx
  src/components/News/News.jsx
  src/components/News/ReadCTA.jsx
  src/components/Phoning/CreateEdit/CreateEdit.jsx
  src/components/Ripostes/Ripostes.jsx
  src/components/Signup/Signup.jsx
  src/components/Signup/components/LegalContainer.jsx
  src/components/Surveys/CreateEdit/CreateEdit.jsx
  src/components/Surveys/Surveys.jsx
  src/providers/query.jsx
  yarn.lock
Labels: Ready for code review

#1948 Create - update committees
  src/api/committees.js
  src/components/Committees/Committees.jsx
  src/components/Committees/CreateEditModal.jsx
  src/components/Committees/Zone/Accordions.jsx
  src/components/Committees/Zone/ZoneItem.jsx
  src/components/Committees/ZonesList.jsx
  src/shared/constants.js
Labels: Ready for code review

#1949 Add remove zone action
  src/components/Committees/CreateEditModal.jsx
  src/components/Committees/Zone/Accordions.jsx
  src/shared/constants.js
Labels: Ready for code review

#1950 fix general meetings reports form error
  src/components/GeneralReports/CreateEditModal.jsx
Labels: Ready for code review

#1951 add map on committee
  src/components/Committees/CreateEditModal.jsx
  src/components/Committees/Map.jsx
  src/components/Committees/Panel.jsx
  src/components/Committees/Zone/Accordions.jsx
  src/components/Committees/Zone/ZoneItem.jsx
  src/components/Committees/ZonesList.jsx
  src/components/Committees/constants.js
  src/domain/zone.js
  src/shared/constants.js
Labels: Ready for code review

#1952 add documents list
  src/api/documents.js
  src/components/Documents/Documents.jsx
  src/components/Documents/index.jsx
  src/components/GeneralReports/GeneralReports.jsx
  src/providers/routes.jsx
  src/shared/features.js
  src/shared/paths.js
Labels: Ready for code review
