Repository parti-renaissance/espace-cadre, pull requests merged in 2024-03, with the labels that each got.

#2911 refactor(event): multiples fixes with the review
  cypress/e2e/events.cy.js
  cypress/fixtures/events/event.json
  src/api/events.js
  src/components/Events/pages/create/CreateEvent.tsx
  src/components/Events/pages/create/components/forms/visibility.tsx
  src/components/Events/pages/list/ListEvents.tsx
  src/components/Events/pages/list/components/CardEvent/CardEvent.tsx
  src/components/Events/pages/list/components/CardEvent/components/actionPopOver.tsx
  src/components/Events/pages/list/components/EventList.tsx
  src/components/Events/shared/constants.ts
  src/components/Events/shared/types.ts
  src/domain/event.ts
  src/domain/place.js
  src/shared/features.js
Labels: bug

#2906 Feature/events v2 1210 — Page Detail Event
  cypress/e2e/events.cy.js
  package.json
  scripts/theme/figma-colors copy.json
  scripts/theme/generated-colors_vox.ts
  src/App.jsx
  src/api/events.js
  src/api/messagerie.ts
  src/components/Dashboard/Charts/SentEmailCampaigns/MessageCard.tsx
  src/components/Events/Components/ModalBeforeLeave.tsx
  src/components/Events/index.jsx
  src/components/Events/pages/createOrEdit/CreateOrEditEvent.tsx
  src/components/Events/pages/createOrEdit/components/BlockForm/BlockForm.tsx
  src/components/Events/pages/createOrEdit/components/FormGroup/FormGroup.tsx
  src/components/Events/pages/createOrEdit/components/TextFieldPlaces.tsx
  src/components/Events/pages/createOrEdit/components/forms/category.tsx
  src/components/Events/pages/createOrEdit/components/forms/uploadImage.tsx
  src/components/Events/pages/createOrEdit/components/forms/visibility.tsx
  src/components/Events/pages/detail/DetailEvent.tsx
  src/components/Events/pages/detail/components/Attendees/Attendees.tsx
  src/components/Events/pages/detail/components/Attendees/index.ts
  src/components/Events/pages/detail/components/ListInformations/ListInformations.tsx
  src/components/Events/pages/detail/components/ListInformations/index.ts
  src/components/Events/pages/detail/components/ShareLink/ShareLink.tsx
  src/components/Events/pages/detail/components/ShareLink/index.ts
  src/components/Events/pages/detail/components/index.ts
  src/components/Events/pages/index.ts
  src/components/Events/pages/list/ListEvents.tsx
  src/components/Events/pages/list/components/CardEvent/CardEvent.tsx
  src/components/Events/pages/list/components/CardEvent/components/actionPopOver.tsx
  src/components/Events/pages/list/components/CardEvent/components/badgeStatus.tsx
  src/components/Events/pages/list/components/CardEvent/helpers.ts
  src/components/Events/shared/constants.ts
  src/components/Events/shared/helpers.ts
  src/components/Events/shared/types.ts
  src/components/Layout/Header.jsx
  src/components/MailsStatutory/SendMail.jsx
  src/components/Messagerie/Card.jsx
  src/components/Messagerie/pages/dashboard.tsx
  src/components/Messagerie/pages/manage/editor/newsletter/index.tsx
  src/components/Messagerie/pages/manage/type/index.tsx
  src/domain/event.ts
  src/shared/helpers.js
  tsconfig.json
  yarn.lock
Labels: enhancement

#2941 [Event] fix committee event creation
  src/api/events.js
  src/api/events.test.js
  src/components/Elections/ElectionFilters.jsx
  src/components/Events/index.jsx
  src/components/Events/pages/createOrEdit/CreateOrEditEvent.tsx
  src/components/Events/pages/list/ListEvents.tsx
  src/components/Events/pages/list/components/CardEvent/CardEvent.tsx
  src/components/Events/shared/constants.ts
  src/domain/event.ts
  src/shared/timezones.json
Labels: bug, Ready for code review
